### ISSUE TITLE
USER STORY: create username

### ISSUE THREAD

**Issue by Kimskogfelter** [Kimskogfelter/My-first-agile-project#7]
As a **user**, I can **choose a username** so that **i can log in on the desired website**

# Acceptance criteria:
 * Acceptance criteria 1
 * Acceptance criteria 2 
 * Acceptance criteria 3

# Tasks
 - [ ] create input where the user choose their username
 - [ ] make sure the user isnt using only numbers or personal information
 - [ ] make sure the  username is available
